### PR TITLE
Polymer 3 conversion

### PR DESCRIPTION
**Pull request by margaree**
Post-script run, the demo didn't work correctly. Moving this script https://github.com/BrightspaceUI/scroll-spy/blob/master/demo/index.html#L97 back to where it was located before (i.e., just within the body tag) fixed this (it had ended up being located within the innerHtml of a template within a script, which didn't seem to work).

### CODE REVIEW

**Comment by dbatiste** [comment]
Reminder to create the `hybrid` branch before merging.  :)

**Comment by svanherk** [comment]
I think tests are failing because we need `OS X 10.13` in `wct.conf.json`.  You can make those changes on master, make the `hybrid` branch, and then either add those changes here or re-run the script

**Comment by margaree** [comment]
ah okay, thanks! - since I've already made the hybrid branch, does it make sense for me to make that change here and then cherry pick the commit into hybrid, or does that complicate things too much?

**Comment by dbatiste** [comment]
At times I've contemplated putting that wct.conf file in a shared place and copying it during npm install step.

**Comment by dbatiste** [comment]
We can delete the hybrid branch and recreate it.

**Comment by svanherk** [comment]
This looks good to me, what will the patch be?  A combination of https://github.com/BrightspaceUI/scroll-spy/pull/5/commits/a70f3b4a2ce834dd22fe24d3d8ef6245fb5ed487 and https://github.com/BrightspaceUI/scroll-spy/pull/5/commits/de4a80093c1c7bcc047059a16481d395e265d98e?

**Comment by margaree** [comment]
yeah, I think it's safe for me to modify https://github.com/BrightspaceUI/scroll-spy/commit/a70f3b4a2ce834dd22fe24d3d8ef6245fb5ed487.patch to remove the @@ -4,9 +4,9 @@ section since the lines don't change

**Pull request merged**
